### ISSUE TITLE
No mongoDB connection!

### ISSUE THREAD

**Issue by dicarez** [stanstrup/PredRet#69]
Error reported while using the server. Unable to process any data file.

**Comment by stanstrup** [comment]
Thanks for reporting. Should be fixed now.

**Comment by Dorrain** [comment]
Hi Jan. I am experiencing some problems while trying to “process and add data” after uploading the csv file. An error message pops up saying: the application expectedly exited. Could you please look into this? Thanks.

**Comment by stanstrup** [comment]
Could you send me a sample file? Then I look into next week.
The system is not very robust so could you check that it is comma separated and not something else?

**Comment by dicarez** [comment]
I also experience the same issue in my latest attempt of using the server.
I have a large list of retention time to estimate from a LC-MS result, so I
imagined the extension of the data could be a problem. I send you the
sample file.
Thank you very much.

2017-10-14 3:46 GMT-03:00 Jan Stanstrup <notifications@github.com>:

**Comment by stanstrup** [comment]
Hi. Could you send the sample to stanstrup@gmail.com?
I see that I had an old email address listed.

**Comment by dicarez** [comment]
Of course, here it is.
Thanks.

2017-10-17 4:18 GMT-03:00 Jan Stanstrup <notifications@github.com>:

**Comment by stanstrup** [comment]
I don't see anything wrong with the formatting of the file.
But the method column should match the name of a system you have created in the "add or modify system" tab.

If that doesn't solve it could you try a subset of the data to see if it indeed chokes at something?

Btw.: How come the retention times are discrete like that? Also I assume these are not experimental retention times?
