### ISSUE TITLE
Server appears busy

### ISSUE THREAD

**Issue by Dorrain** [stanstrup/PredRet#74]
Hi Jan. Thanks for resolving the DB mongo connection. There seems to be another problem, the server appears to be busy and i can't seem to upload the data. 

![error reading from remote server](https://user-images.githubusercontent.com/32770349/34771757-fcb155da-f605-11e7-8091-0d6e8c5b91f7.png)

**Comment by stanstrup** [comment]
Seems to work here. Could you try again?
