### ISSUE TITLE
The application unexpectedly exited.

### ISSUE THREAD

**Issue by soallard** [stanstrup/PredRet#75]
Hello,

This is the first time I try using the Predret website, after having uploaded my data when I click on the Process & Add data button I have this error message:

"The application unexpectedly exited.
Diagnostic information has been dumped to the JavaScript error console."

Information on the the JavaScript console:
![](https://user-images.githubusercontent.com/36474770/36201189-70d3ee84-117f-11e8-9395-9a1cb4713626.png)

I have tried on different web browsers with no success.

Thanks for your help,

Sophie

**Comment by stanstrup** [comment]
Dear Sophie,

probably it is because the app is not very robust to the way the CSV file
is formatted. You need to be sure it is really comma separated and not
something else. If you send me the file I can track down the issue.

Best,
Jan.

**Comment by soallard** [comment]
Hello,

Here is the csv file I'am using.
Thank you for your help.

Sophie

2018-02-18 15:31 GMT+01:00 Jan Stanstrup <notifications@github.com>:

**Comment by stanstrup** [comment]
Can you send it to my email? stanstrup@gmail.com
Email attachments doesn't seem to go through.

**Comment by stanstrup** [comment]
the problem is that the InChI's contain commas also. Your spreadsheet program need to put quotes around the InChI's. it is basically not a valid csv file.

**Comment by stanstrup** [comment]
Sorry about that. The database crashed apparently. It should work now.
