### ISSUE TITLE
“No mongoDB connection”

### ISSUE THREAD

**Issue by Dorrain** [stanstrup/PredRet#76]
There is an error message on PredRet saying, “No mongoDB connection”.

**Comment by stanstrup** [comment]
Thanks.

Damn. I thought I was beyond this issue when I added more space to the server. Logs don't say what happened :(

But it is running again.

**Comment by Dorrain** [comment]
Thanks for fixing the issue.
I am going to add more data and systems to PredRet, hopefully it goes smoothly.

Cheers,
Dorrain

De : Jan Stanstrup <notifications@github.com>
Envoyé : mardi 19 juin 2018 16:34
À : stanstrup/PredRet <PredRet@noreply.github.com>
Cc : Dorrain Low-Yanwen <dorrain.low-yanwen@inra.fr>; Author <author@noreply.github.com>
Objet : Re: [stanstrup/PredRet] “No mongoDB connection” (#76)


Thanks.

Damn. I thought I was beyond this issue when I added more space to the server. Logs don't say what happened :(

But it is running again.
