### ISSUE TITLE
Retention time prediction tool "socket hang up" error

### ISSUE THREAD

**Issue by jonstrutz11** [stanstrup/PredRet#77]
I used the retention time prediction tool a few days ago. However, now when I try to use it I get the following error:

![image](https://user-images.githubusercontent.com/23544847/53028076-cbdce400-342b-11e9-9df7-9211dfe4980d.png)

I tried clearing my browser cache and using a different browser with the same results. I first saw this yesterday and it is still happening today. I also tried setting up a new user account, but got the same error. Finally, I tried using the retention time prediction tool on my iPhone (in safari web browser) and got the same result, except on my phone it also says below "socket hang up":

"Listening on http://127.0.0.1:38013
Loading required package: rJava
Loading required package: xlsxjars
Loading required package: Rcpp"

which might be useful for resolving the issue?

**Comment by jonstrutz11** [comment]
The browser I'm using is Google Chrome 72.0.3626.109

Let me know if you'd like any other information!

**Comment by stanstrup** [comment]
Sorry about that. That is my server running out of memory. I am paying out of pocket at the moment for the hosting so I am driving a bit close to the limits to keep costs down.
I have rebooted and it is back to business now.

**Comment by jonstrutz11** [comment]
Great, it seems to be working again, thank you!
