### ISSUE TITLE
Upload Data Error

### ISSUE THREAD

**Issue by qaporter** [stanstrup/PredRet#78]
![Upload Data](https://user-images.githubusercontent.com/49765364/56386654-653c3280-61f0-11e9-9b3c-341a76c1929c.png)
![Upload Data](https://user-images.githubusercontent.com/49765364/56387171-9e28d700-61f1-11e9-8bc4-7b0fbca6ae36.png)

Hi, I am trying to use to predret to predicted retention time, but I am having a problem uploading the data.

**Comment by stanstrup** [comment]
Thanks. Sorry for the long response time. It is vacation time here.
The problem is that the pubchem API changed so predret cannot pull the structure. If instead you put in the inchi manually it should work.
Same as https://github.com/stanstrup/PredRet/issues/72
