### ISSUE TITLE
How to run the PredRet within R?

### ISSUE THREAD

**Issue by Danissss** [stanstrup/PredRet#81]
Could you provide any sample run command and the result?

**Comment by stanstrup** [comment]
Depends what you want to do.
With the package you can pull information from the database. But not, for example add data, or do the modeling.

See here for just getting data: http://stanstrup.github.io/annotate_with_PredRet.html
`PredRet_get_chrom_systems` can be used to see what systems are in the database.

**Comment by Danissss** [comment]
Thanks!

**Comment by Danissss** [comment]
Hi,
Sorry, I was confused.
After I installed everything
```
install.packages("devtools")
library(devtools)

source("https://bioconductor.org/biocLite.R")
biocLite("pcaMethods")

install_github("mongosoup/rmongodb")
install_github("stanstrup/Rplot.extra")
install_github("stanstrup/massageR")

install_github("stanstrup/PredRet",subdir = "PredRetR")
```
How should I achieve Retention Time Prediction (from your paper) procedure using R instead of using web interface?

I have list of inchi (rt may not be available for every compounds).

Thank you!

**Comment by stanstrup** [comment]
You cannot. Sorry. You have to use the web interface.
You can only download data (and predictions) from R. You cannot add data to the system.

**Comment by Danissss** [comment]
Yes, I only want to do predictions from R. I am not going to add data to system.

**Comment by stanstrup** [comment]
The system doesn't work like that. You _cannot_ make predictions for a system if data has not been uploaded for that system.
You can download existing predictions from R. But not "make" predictions.
