### ISSUE TITLE
Run Time Estimate

### ISSUE THREAD

**Issue by angepoch** [stanstrup/PredRet#83]
Hello!

First, thank you for creating this tool, it will really help with the untargeted metabolomics annotation process.

I was wondering what is the approximate time it takes to get predictions for our data. The website says approx. 30 minutes, but I have run it for over 24 hours and it is still not showing on my end. 

Thanks in advance for your help!

**Comment by stanstrup** [comment]
Which is your dataset? Perhaps it wasn't able to make any models.

**Comment by angepoch** [comment]
Hello, 

It ended up showing after ~48 hours. There must have been a lot of data queued ahead of me.

Thanks!

**Comment by stanstrup** [comment]
Right. It is possible to takes much longer now than before. Since it is making models one system against one system the number of calculations grows by ~N^2 for the number of systems in the database. It has grown significantly since it was developed.
